# ************************************************************************
#  @author:     Andreas Kaeberlein
#  @copyright:  Copyright 2021
#  @credits:    AKAE
#
#  @license:    BSDv3
#  @maintainer: Andreas Kaeberlein
#  @email:      andreas.kaeberlein@web.de
#
#  @file:       unittest.yml
#  @date:       2021-09-01
#
#  @brief:      runs test and deploy
#
# ************************************************************************


name: Unittest

on:
  push:
    paths-ignore:
      - 'doc/**'
      - 'README.md'

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      GHDL_OPTS: "--std=93c --ieee=synopsys --time-resolution=ps --workdir=./sim/work"
    steps:
      - uses: actions/checkout@v4
      - uses: ghdl/setup-ghdl@v1
        with:
          version: nightly
          backend: mcode
      - name: Prepare
        run: |
          ghdl --version
          mkdir -p ./sim/work
      - name: tiny_uart_inp_filter
        run: |
          ghdl -a ${GHDL_OPTS} ${GITHUB_WORKSPACE}/hdl/tiny_uart_inp_filter.vhd
          ghdl -a ${GHDL_OPTS} ${GITHUB_WORKSPACE}/tb/tiny_uart_inp_filter_tb.vhd
          ((ghdl -r ${GHDL_OPTS} tiny_uart_inp_filter_tb -gDO_ALL_TEST=True) || if [ $? -ne 0 ]; then echo "[ FAIL ]   tiny_uart_inp_filter_tb"; exit 1; fi)
      - name: tiny_uart_baud_bit_gen
        run: |
          ghdl -a ${GHDL_OPTS} ${GITHUB_WORKSPACE}/hdl/tiny_uart_baud_bit_gen.vhd
          ghdl -a ${GHDL_OPTS} ${GITHUB_WORKSPACE}/tb/tiny_uart_baud_bit_gen_tb.vhd
          ((ghdl -r ${GHDL_OPTS} tiny_uart_baud_bit_gen_tb -gDO_ALL_TEST=True) || if [ $? -ne 0 ]; then echo "[ FAIL ]   tiny_uart_baud_bit_gen_tb"; exit 1; fi)
      - name: tiny_uart
        run: |
          ghdl -a ${GHDL_OPTS} ${GITHUB_WORKSPACE}/hdl/tiny_uart_inp_filter.vhd
          ghdl -a ${GHDL_OPTS} ${GITHUB_WORKSPACE}/hdl/tiny_uart_baud_bit_gen.vhd
          ghdl -a ${GHDL_OPTS} ${GITHUB_WORKSPACE}/hdl/tiny_uart.vhd
          ghdl -a ${GHDL_OPTS} ${GITHUB_WORKSPACE}/tb/tiny_uart_tb.vhd
          ((ghdl -r ${GHDL_OPTS} tiny_uart_tb -gDO_ALL_TEST=True) || if [ $? -ne 0 ]; then echo "[ FAIL ]   tiny_uart_tb"; exit 1; fi)
